on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: deploy2nekoweb
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.13.0
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.11.0
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build bsky-pathfinder
        working-directory: ./bsky-pathfinder
        run: |
          pnpm install
          npm build

      - name: Build site
        run: pnpm build

      - name: deploy2nekoweb
        uses: deploy2nekoweb/deploy2nekoweb@v4
        with:
          nekoweb-api-key: ${{ secrets.NEKOWEB_API_KEY }}
          nekoweb-cookie: ${{ secrets.NEKOWEB_COOKIE }}
          nekoweb-folder: "public"
          directory: "public"
